// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package upvote_controller

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpvoteControllerClient is the client API for UpvoteController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpvoteControllerClient interface {
	GetUpvote(ctx context.Context, in *IdDTO, opts ...grpc.CallOption) (*GetUpvoteDTO, error)
	CreateUpvote(ctx context.Context, in *CreateUpvoteDTO, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteUpvote(ctx context.Context, in *IdDTO, opts ...grpc.CallOption) (*empty.Empty, error)
}

type upvoteControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewUpvoteControllerClient(cc grpc.ClientConnInterface) UpvoteControllerClient {
	return &upvoteControllerClient{cc}
}

func (c *upvoteControllerClient) GetUpvote(ctx context.Context, in *IdDTO, opts ...grpc.CallOption) (*GetUpvoteDTO, error) {
	out := new(GetUpvoteDTO)
	err := c.cc.Invoke(ctx, "/KleverTechnicalChallenge.UpvoteController/GetUpvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upvoteControllerClient) CreateUpvote(ctx context.Context, in *CreateUpvoteDTO, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/KleverTechnicalChallenge.UpvoteController/CreateUpvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upvoteControllerClient) DeleteUpvote(ctx context.Context, in *IdDTO, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/KleverTechnicalChallenge.UpvoteController/DeleteUpvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpvoteControllerServer is the server API for UpvoteController service.
// All implementations must embed UnimplementedUpvoteControllerServer
// for forward compatibility
type UpvoteControllerServer interface {
	GetUpvote(context.Context, *IdDTO) (*GetUpvoteDTO, error)
	CreateUpvote(context.Context, *CreateUpvoteDTO) (*empty.Empty, error)
	DeleteUpvote(context.Context, *IdDTO) (*empty.Empty, error)
	mustEmbedUnimplementedUpvoteControllerServer()
}

// UnimplementedUpvoteControllerServer must be embedded to have forward compatible implementations.
type UnimplementedUpvoteControllerServer struct {
}

func (UnimplementedUpvoteControllerServer) GetUpvote(context.Context, *IdDTO) (*GetUpvoteDTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpvote not implemented")
}
func (UnimplementedUpvoteControllerServer) CreateUpvote(context.Context, *CreateUpvoteDTO) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUpvote not implemented")
}
func (UnimplementedUpvoteControllerServer) DeleteUpvote(context.Context, *IdDTO) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUpvote not implemented")
}
func (UnimplementedUpvoteControllerServer) mustEmbedUnimplementedUpvoteControllerServer() {}

// UnsafeUpvoteControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpvoteControllerServer will
// result in compilation errors.
type UnsafeUpvoteControllerServer interface {
	mustEmbedUnimplementedUpvoteControllerServer()
}

func RegisterUpvoteControllerServer(s grpc.ServiceRegistrar, srv UpvoteControllerServer) {
	s.RegisterService(&UpvoteController_ServiceDesc, srv)
}

func _UpvoteController_GetUpvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvoteControllerServer).GetUpvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KleverTechnicalChallenge.UpvoteController/GetUpvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvoteControllerServer).GetUpvote(ctx, req.(*IdDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpvoteController_CreateUpvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpvoteDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvoteControllerServer).CreateUpvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KleverTechnicalChallenge.UpvoteController/CreateUpvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvoteControllerServer).CreateUpvote(ctx, req.(*CreateUpvoteDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpvoteController_DeleteUpvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpvoteControllerServer).DeleteUpvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KleverTechnicalChallenge.UpvoteController/DeleteUpvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpvoteControllerServer).DeleteUpvote(ctx, req.(*IdDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// UpvoteController_ServiceDesc is the grpc.ServiceDesc for UpvoteController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpvoteController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KleverTechnicalChallenge.UpvoteController",
	HandlerType: (*UpvoteControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUpvote",
			Handler:    _UpvoteController_GetUpvote_Handler,
		},
		{
			MethodName: "CreateUpvote",
			Handler:    _UpvoteController_CreateUpvote_Handler,
		},
		{
			MethodName: "DeleteUpvote",
			Handler:    _UpvoteController_DeleteUpvote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controllers/upvote_controller/upvote.proto",
}
