// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: controllers/upvote_controller/upvote.proto

package upvote_controller

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_upvote   Type = 0
	Type_downvote Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "upvote",
		1: "downvote",
	}
	Type_value = map[string]int32{
		"upvote":   0,
		"downvote": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_controllers_upvote_controller_upvote_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_controllers_upvote_controller_upvote_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_controllers_upvote_controller_upvote_proto_rawDescGZIP(), []int{0}
}

type IdDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdDTO) Reset() {
	*x = IdDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdDTO) ProtoMessage() {}

func (x *IdDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdDTO.ProtoReflect.Descriptor instead.
func (*IdDTO) Descriptor() ([]byte, []int) {
	return file_controllers_upvote_controller_upvote_proto_rawDescGZIP(), []int{0}
}

func (x *IdDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUpvoteDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt string `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Type      Type   `protobuf:"varint,3,opt,name=type,proto3,enum=KleverTechnicalChallenge.Type" json:"type,omitempty"`
	CommentId string `protobuf:"bytes,4,opt,name=commentId,proto3" json:"commentId,omitempty"`
}

func (x *GetUpvoteDTO) Reset() {
	*x = GetUpvoteDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUpvoteDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpvoteDTO) ProtoMessage() {}

func (x *GetUpvoteDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpvoteDTO.ProtoReflect.Descriptor instead.
func (*GetUpvoteDTO) Descriptor() ([]byte, []int) {
	return file_controllers_upvote_controller_upvote_proto_rawDescGZIP(), []int{1}
}

func (x *GetUpvoteDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUpvoteDTO) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetUpvoteDTO) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_upvote
}

func (x *GetUpvoteDTO) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type CreateUpvoteDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Type   `protobuf:"varint,1,opt,name=type,proto3,enum=KleverTechnicalChallenge.Type" json:"type,omitempty"`
	CommentId string `protobuf:"bytes,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
}

func (x *CreateUpvoteDTO) Reset() {
	*x = CreateUpvoteDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUpvoteDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpvoteDTO) ProtoMessage() {}

func (x *CreateUpvoteDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_upvote_controller_upvote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpvoteDTO.ProtoReflect.Descriptor instead.
func (*CreateUpvoteDTO) Descriptor() ([]byte, []int) {
	return file_controllers_upvote_controller_upvote_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUpvoteDTO) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_upvote
}

func (x *CreateUpvoteDTO) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

var File_controllers_upvote_controller_upvote_proto protoreflect.FileDescriptor

var file_controllers_upvote_controller_upvote_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x75, 0x70,
	0x76, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f,
	0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x4b, 0x6c,
	0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x05, 0x49, 0x64, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8e, 0x01, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x4b, 0x6c, 0x65, 0x76,
	0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x63, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x54, 0x4f,
	0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x2a, 0x20, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x70,
	0x76, 0x6f, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x76, 0x6f,
	0x74, 0x65, 0x10, 0x01, 0x32, 0x8a, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x2e, 0x49, 0x64, 0x44, 0x54, 0x4f, 0x1a, 0x26, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72,
	0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x54, 0x4f, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x12, 0x29, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x54, 0x4f, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x2e, 0x49, 0x64, 0x44, 0x54, 0x4f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x73, 0x2f, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controllers_upvote_controller_upvote_proto_rawDescOnce sync.Once
	file_controllers_upvote_controller_upvote_proto_rawDescData = file_controllers_upvote_controller_upvote_proto_rawDesc
)

func file_controllers_upvote_controller_upvote_proto_rawDescGZIP() []byte {
	file_controllers_upvote_controller_upvote_proto_rawDescOnce.Do(func() {
		file_controllers_upvote_controller_upvote_proto_rawDescData = protoimpl.X.CompressGZIP(file_controllers_upvote_controller_upvote_proto_rawDescData)
	})
	return file_controllers_upvote_controller_upvote_proto_rawDescData
}

var file_controllers_upvote_controller_upvote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controllers_upvote_controller_upvote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_controllers_upvote_controller_upvote_proto_goTypes = []interface{}{
	(Type)(0),               // 0: KleverTechnicalChallenge.Type
	(*IdDTO)(nil),           // 1: KleverTechnicalChallenge.IdDTO
	(*GetUpvoteDTO)(nil),    // 2: KleverTechnicalChallenge.GetUpvoteDTO
	(*CreateUpvoteDTO)(nil), // 3: KleverTechnicalChallenge.CreateUpvoteDTO
	(*empty.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_controllers_upvote_controller_upvote_proto_depIdxs = []int32{
	0, // 0: KleverTechnicalChallenge.GetUpvoteDTO.type:type_name -> KleverTechnicalChallenge.Type
	0, // 1: KleverTechnicalChallenge.CreateUpvoteDTO.type:type_name -> KleverTechnicalChallenge.Type
	1, // 2: KleverTechnicalChallenge.UpvoteController.GetUpvote:input_type -> KleverTechnicalChallenge.IdDTO
	3, // 3: KleverTechnicalChallenge.UpvoteController.CreateUpvote:input_type -> KleverTechnicalChallenge.CreateUpvoteDTO
	1, // 4: KleverTechnicalChallenge.UpvoteController.DeleteUpvote:input_type -> KleverTechnicalChallenge.IdDTO
	2, // 5: KleverTechnicalChallenge.UpvoteController.GetUpvote:output_type -> KleverTechnicalChallenge.GetUpvoteDTO
	4, // 6: KleverTechnicalChallenge.UpvoteController.CreateUpvote:output_type -> google.protobuf.Empty
	4, // 7: KleverTechnicalChallenge.UpvoteController.DeleteUpvote:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controllers_upvote_controller_upvote_proto_init() }
func file_controllers_upvote_controller_upvote_proto_init() {
	if File_controllers_upvote_controller_upvote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controllers_upvote_controller_upvote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controllers_upvote_controller_upvote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUpvoteDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controllers_upvote_controller_upvote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUpvoteDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controllers_upvote_controller_upvote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controllers_upvote_controller_upvote_proto_goTypes,
		DependencyIndexes: file_controllers_upvote_controller_upvote_proto_depIdxs,
		EnumInfos:         file_controllers_upvote_controller_upvote_proto_enumTypes,
		MessageInfos:      file_controllers_upvote_controller_upvote_proto_msgTypes,
	}.Build()
	File_controllers_upvote_controller_upvote_proto = out.File
	file_controllers_upvote_controller_upvote_proto_rawDesc = nil
	file_controllers_upvote_controller_upvote_proto_goTypes = nil
	file_controllers_upvote_controller_upvote_proto_depIdxs = nil
}
