// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: controllers/comment_controller/comment.proto

package comment_controller

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommentDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetCommentDTO) Reset() {
	*x = GetCommentDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_comment_controller_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentDTO) ProtoMessage() {}

func (x *GetCommentDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_comment_controller_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentDTO.ProtoReflect.Descriptor instead.
func (*GetCommentDTO) Descriptor() ([]byte, []int) {
	return file_controllers_comment_controller_comment_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommentDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCommentDTO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCommentDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateCommentDTO) Reset() {
	*x = CreateCommentDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_comment_controller_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentDTO) ProtoMessage() {}

func (x *CreateCommentDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_comment_controller_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentDTO.ProtoReflect.Descriptor instead.
func (*CreateCommentDTO) Descriptor() ([]byte, []int) {
	return file_controllers_comment_controller_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentDTO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllCommentDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comments []*GetCommentDTO `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *GetAllCommentDTO) Reset() {
	*x = GetAllCommentDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controllers_comment_controller_comment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCommentDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommentDTO) ProtoMessage() {}

func (x *GetAllCommentDTO) ProtoReflect() protoreflect.Message {
	mi := &file_controllers_comment_controller_comment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommentDTO.ProtoReflect.Descriptor instead.
func (*GetAllCommentDTO) Descriptor() ([]byte, []int) {
	return file_controllers_comment_controller_comment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllCommentDTO) GetComments() []*GetCommentDTO {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_controllers_comment_controller_comment_proto protoreflect.FileDescriptor

var file_controllers_comment_controller_comment_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x54, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x57,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44,
	0x54, 0x4f, 0x12, 0x43, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63,
	0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xbd, 0x01, 0x0a, 0x0f, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x0d, 0x66,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2a, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63,
	0x68, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x54, 0x4f,
	0x22, 0x00, 0x12, 0x53, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x12, 0x2a, 0x2e, 0x4b, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x2e, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_controllers_comment_controller_comment_proto_rawDescOnce sync.Once
	file_controllers_comment_controller_comment_proto_rawDescData = file_controllers_comment_controller_comment_proto_rawDesc
)

func file_controllers_comment_controller_comment_proto_rawDescGZIP() []byte {
	file_controllers_comment_controller_comment_proto_rawDescOnce.Do(func() {
		file_controllers_comment_controller_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_controllers_comment_controller_comment_proto_rawDescData)
	})
	return file_controllers_comment_controller_comment_proto_rawDescData
}

var file_controllers_comment_controller_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_controllers_comment_controller_comment_proto_goTypes = []interface{}{
	(*GetCommentDTO)(nil),    // 0: KleverTechnicalChallenge.GetCommentDTO
	(*CreateCommentDTO)(nil), // 1: KleverTechnicalChallenge.CreateCommentDTO
	(*GetAllCommentDTO)(nil), // 2: KleverTechnicalChallenge.GetAllCommentDTO
	(*empty.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_controllers_comment_controller_comment_proto_depIdxs = []int32{
	0, // 0: KleverTechnicalChallenge.GetAllCommentDTO.comments:type_name -> KleverTechnicalChallenge.GetCommentDTO
	3, // 1: KleverTechnicalChallenge.AlbumController.findAllAlbums:input_type -> google.protobuf.Empty
	1, // 2: KleverTechnicalChallenge.AlbumController.createAlbum:input_type -> KleverTechnicalChallenge.CreateCommentDTO
	2, // 3: KleverTechnicalChallenge.AlbumController.findAllAlbums:output_type -> KleverTechnicalChallenge.GetAllCommentDTO
	3, // 4: KleverTechnicalChallenge.AlbumController.createAlbum:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controllers_comment_controller_comment_proto_init() }
func file_controllers_comment_controller_comment_proto_init() {
	if File_controllers_comment_controller_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controllers_comment_controller_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controllers_comment_controller_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controllers_comment_controller_comment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCommentDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controllers_comment_controller_comment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controllers_comment_controller_comment_proto_goTypes,
		DependencyIndexes: file_controllers_comment_controller_comment_proto_depIdxs,
		MessageInfos:      file_controllers_comment_controller_comment_proto_msgTypes,
	}.Build()
	File_controllers_comment_controller_comment_proto = out.File
	file_controllers_comment_controller_comment_proto_rawDesc = nil
	file_controllers_comment_controller_comment_proto_goTypes = nil
	file_controllers_comment_controller_comment_proto_depIdxs = nil
}
