// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package comment_controller

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentControllerClient is the client API for CommentController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentControllerClient interface {
	GetAllComments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllCommentDTO, error)
	CreateComment(ctx context.Context, in *CreateCommentDTO, opts ...grpc.CallOption) (*empty.Empty, error)
}

type commentControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentControllerClient(cc grpc.ClientConnInterface) CommentControllerClient {
	return &commentControllerClient{cc}
}

func (c *commentControllerClient) GetAllComments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllCommentDTO, error) {
	out := new(GetAllCommentDTO)
	err := c.cc.Invoke(ctx, "/KleverTechnicalChallenge.CommentController/GetAllComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentControllerClient) CreateComment(ctx context.Context, in *CreateCommentDTO, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/KleverTechnicalChallenge.CommentController/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentControllerServer is the server API for CommentController service.
// All implementations must embed UnimplementedCommentControllerServer
// for forward compatibility
type CommentControllerServer interface {
	GetAllComments(context.Context, *empty.Empty) (*GetAllCommentDTO, error)
	CreateComment(context.Context, *CreateCommentDTO) (*empty.Empty, error)
	mustEmbedUnimplementedCommentControllerServer()
}

// UnimplementedCommentControllerServer must be embedded to have forward compatible implementations.
type UnimplementedCommentControllerServer struct {
}

func (UnimplementedCommentControllerServer) GetAllComments(context.Context, *empty.Empty) (*GetAllCommentDTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllComments not implemented")
}
func (UnimplementedCommentControllerServer) CreateComment(context.Context, *CreateCommentDTO) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentControllerServer) mustEmbedUnimplementedCommentControllerServer() {}

// UnsafeCommentControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentControllerServer will
// result in compilation errors.
type UnsafeCommentControllerServer interface {
	mustEmbedUnimplementedCommentControllerServer()
}

func RegisterCommentControllerServer(s grpc.ServiceRegistrar, srv CommentControllerServer) {
	s.RegisterService(&CommentController_ServiceDesc, srv)
}

func _CommentController_GetAllComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentControllerServer).GetAllComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KleverTechnicalChallenge.CommentController/GetAllComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentControllerServer).GetAllComments(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentController_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentControllerServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KleverTechnicalChallenge.CommentController/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentControllerServer).CreateComment(ctx, req.(*CreateCommentDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentController_ServiceDesc is the grpc.ServiceDesc for CommentController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KleverTechnicalChallenge.CommentController",
	HandlerType: (*CommentControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllComments",
			Handler:    _CommentController_GetAllComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _CommentController_CreateComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controllers/comment_controller/comment.proto",
}
